// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/model/post.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_Draft   Status = 0
	Status_Publish Status = 1
)

var Status_name = map[int32]string{
	0: "Draft",
	1: "Publish",
}

var Status_value = map[string]int32{
	"Draft":   0,
	"Publish": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d09315a8de3a1c1f, []int{0}
}

type Post struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_d09315a8de3a1c1f, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type PostList struct {
	List                 []*Post  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostList) Reset()         { *m = PostList{} }
func (m *PostList) String() string { return proto.CompactTextString(m) }
func (*PostList) ProtoMessage()    {}
func (*PostList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d09315a8de3a1c1f, []int{1}
}

func (m *PostList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostList.Unmarshal(m, b)
}
func (m *PostList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostList.Marshal(b, m, deterministic)
}
func (m *PostList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostList.Merge(m, src)
}
func (m *PostList) XXX_Size() int {
	return xxx_messageInfo_PostList.Size(m)
}
func (m *PostList) XXX_DiscardUnknown() {
	xxx_messageInfo_PostList.DiscardUnknown(m)
}

var xxx_messageInfo_PostList proto.InternalMessageInfo

func (m *PostList) GetList() []*Post {
	if m != nil {
		return m.List
	}
	return nil
}

type PostListByUser struct {
	List                 map[string]*PostList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PostListByUser) Reset()         { *m = PostListByUser{} }
func (m *PostListByUser) String() string { return proto.CompactTextString(m) }
func (*PostListByUser) ProtoMessage()    {}
func (*PostListByUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_d09315a8de3a1c1f, []int{2}
}

func (m *PostListByUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostListByUser.Unmarshal(m, b)
}
func (m *PostListByUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostListByUser.Marshal(b, m, deterministic)
}
func (m *PostListByUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostListByUser.Merge(m, src)
}
func (m *PostListByUser) XXX_Size() int {
	return xxx_messageInfo_PostListByUser.Size(m)
}
func (m *PostListByUser) XXX_DiscardUnknown() {
	xxx_messageInfo_PostListByUser.DiscardUnknown(m)
}

var xxx_messageInfo_PostListByUser proto.InternalMessageInfo

func (m *PostListByUser) GetList() map[string]*PostList {
	if m != nil {
		return m.List
	}
	return nil
}

type PostAndUserId struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Post                 *Post    `protobuf:"bytes,2,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostAndUserId) Reset()         { *m = PostAndUserId{} }
func (m *PostAndUserId) String() string { return proto.CompactTextString(m) }
func (*PostAndUserId) ProtoMessage()    {}
func (*PostAndUserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_d09315a8de3a1c1f, []int{3}
}

func (m *PostAndUserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostAndUserId.Unmarshal(m, b)
}
func (m *PostAndUserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostAndUserId.Marshal(b, m, deterministic)
}
func (m *PostAndUserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostAndUserId.Merge(m, src)
}
func (m *PostAndUserId) XXX_Size() int {
	return xxx_messageInfo_PostAndUserId.Size(m)
}
func (m *PostAndUserId) XXX_DiscardUnknown() {
	xxx_messageInfo_PostAndUserId.DiscardUnknown(m)
}

var xxx_messageInfo_PostAndUserId proto.InternalMessageInfo

func (m *PostAndUserId) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PostAndUserId) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type PostByUserId struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostByUserId) Reset()         { *m = PostByUserId{} }
func (m *PostByUserId) String() string { return proto.CompactTextString(m) }
func (*PostByUserId) ProtoMessage()    {}
func (*PostByUserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_d09315a8de3a1c1f, []int{4}
}

func (m *PostByUserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostByUserId.Unmarshal(m, b)
}
func (m *PostByUserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostByUserId.Marshal(b, m, deterministic)
}
func (m *PostByUserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostByUserId.Merge(m, src)
}
func (m *PostByUserId) XXX_Size() int {
	return xxx_messageInfo_PostByUserId.Size(m)
}
func (m *PostByUserId) XXX_DiscardUnknown() {
	xxx_messageInfo_PostByUserId.DiscardUnknown(m)
}

var xxx_messageInfo_PostByUserId proto.InternalMessageInfo

func (m *PostByUserId) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterEnum("model.Status", Status_name, Status_value)
	proto.RegisterType((*Post)(nil), "model.Post")
	proto.RegisterType((*PostList)(nil), "model.PostList")
	proto.RegisterType((*PostListByUser)(nil), "model.PostListByUser")
	proto.RegisterMapType((map[string]*PostList)(nil), "model.PostListByUser.ListEntry")
	proto.RegisterType((*PostAndUserId)(nil), "model.PostAndUserId")
	proto.RegisterType((*PostByUserId)(nil), "model.PostByUserId")
}

func init() {
	proto.RegisterFile("common/model/post.proto", fileDescriptor_d09315a8de3a1c1f)
}

var fileDescriptor_d09315a8de3a1c1f = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x5d, 0x6b, 0xea, 0x40,
	0x10, 0x35, 0x5f, 0x7a, 0x9d, 0xdc, 0xeb, 0x95, 0xbd, 0x72, 0x0d, 0xe9, 0x83, 0x12, 0x28, 0x95,
	0x16, 0x36, 0xa0, 0x14, 0x4a, 0xdf, 0x2c, 0xb5, 0x54, 0xe8, 0x83, 0x58, 0xfa, 0x5c, 0xd4, 0xac,
	0x36, 0x34, 0xc9, 0x4a, 0x76, 0x52, 0xc8, 0xaf, 0xe8, 0x5f, 0x2e, 0xbb, 0x6b, 0xac, 0xfa, 0xd0,
	0xb7, 0x9d, 0x73, 0x66, 0xce, 0x9e, 0x99, 0x03, 0xdd, 0x15, 0x4f, 0x53, 0x9e, 0x85, 0x29, 0x8f,
	0x58, 0x12, 0x6e, 0xb9, 0x40, 0xba, 0xcd, 0x39, 0x72, 0xe2, 0x28, 0xc4, 0x3f, 0xdb, 0x70, 0xbe,
	0x49, 0x58, 0xa8, 0xc0, 0x65, 0xb1, 0x0e, 0x59, 0xba, 0xc5, 0x52, 0xf7, 0x04, 0x0f, 0x60, 0xcf,
	0xb8, 0x40, 0xd2, 0x02, 0x33, 0x8e, 0x3c, 0xa3, 0x6f, 0x0c, 0x9a, 0x73, 0x33, 0x8e, 0x48, 0x07,
	0x1c, 0x8c, 0x31, 0x61, 0x9e, 0xa9, 0x20, 0x5d, 0x10, 0x0f, 0x1a, 0x2b, 0x9e, 0x21, 0xcb, 0xd0,
	0xb3, 0x14, 0x5e, 0x95, 0xc1, 0x15, 0xfc, 0x92, 0x3a, 0x4f, 0xb1, 0x40, 0xd2, 0x03, 0x3b, 0x89,
	0x05, 0x7a, 0x46, 0xdf, 0x1a, 0xb8, 0x43, 0x97, 0x2a, 0x1b, 0x54, 0xd2, 0x73, 0x45, 0x04, 0x9f,
	0x06, 0xb4, 0xaa, 0xee, 0xbb, 0xf2, 0x45, 0xb0, 0x9c, 0x8c, 0x8e, 0x66, 0x7a, 0x07, 0x33, 0xdf,
	0x4d, 0x54, 0x3e, 0x27, 0x19, 0xe6, 0xa5, 0xd6, 0xf1, 0x1f, 0xa1, 0xb9, 0x87, 0x48, 0x1b, 0xac,
	0x77, 0x56, 0xee, 0x56, 0x90, 0x4f, 0x72, 0x0e, 0xce, 0xc7, 0x22, 0x29, 0xf4, 0x0e, 0xee, 0xf0,
	0xef, 0x89, 0xe8, 0x5c, 0xb3, 0xb7, 0xe6, 0x8d, 0x11, 0x4c, 0xe1, 0x8f, 0x84, 0xc7, 0x59, 0x24,
	0x3f, 0x9a, 0x46, 0xa4, 0x0b, 0x8d, 0x42, 0xb0, 0xfc, 0x75, 0x7f, 0x94, 0x7a, 0xa1, 0x89, 0x1e,
	0xd8, 0xf2, 0xc4, 0x3b, 0xcd, 0xe3, 0xe5, 0x24, 0x11, 0x5c, 0xc0, 0x6f, 0x59, 0x69, 0xcb, 0x3f,
	0x28, 0x5d, 0xf6, 0xa1, 0xfe, 0x8c, 0x0b, 0x2c, 0x04, 0x69, 0x82, 0x73, 0x9f, 0x2f, 0xd6, 0xd8,
	0xae, 0x11, 0x17, 0x1a, 0xb3, 0x62, 0x99, 0xc4, 0xe2, 0xad, 0x6d, 0x0c, 0x33, 0x70, 0xa4, 0x94,
	0x20, 0xd7, 0x60, 0x8d, 0xa3, 0x88, 0x74, 0x0e, 0x7e, 0xdb, 0x5b, 0xf5, 0xff, 0x53, 0x1d, 0x30,
	0xad, 0x02, 0xa6, 0x13, 0x19, 0x70, 0x50, 0x23, 0x14, 0x6c, 0x15, 0xc8, 0xbf, 0x83, 0xb9, 0xca,
	0x97, 0x7f, 0x7a, 0x8e, 0xa0, 0xb6, 0xac, 0x2b, 0x85, 0xd1, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x17, 0x12, 0x22, 0x50, 0x52, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PostsClient is the client API for Posts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostsClient interface {
	Add(ctx context.Context, in *PostAndUserId, opts ...grpc.CallOption) (*empty.Empty, error)
	List(ctx context.Context, in *PostByUserId, opts ...grpc.CallOption) (*PostList, error)
}

type postsClient struct {
	cc grpc.ClientConnInterface
}

func NewPostsClient(cc grpc.ClientConnInterface) PostsClient {
	return &postsClient{cc}
}

func (c *postsClient) Add(ctx context.Context, in *PostAndUserId, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/model.Posts/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsClient) List(ctx context.Context, in *PostByUserId, opts ...grpc.CallOption) (*PostList, error) {
	out := new(PostList)
	err := c.cc.Invoke(ctx, "/model.Posts/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostsServer is the server API for Posts service.
type PostsServer interface {
	Add(context.Context, *PostAndUserId) (*empty.Empty, error)
	List(context.Context, *PostByUserId) (*PostList, error)
}

// UnimplementedPostsServer can be embedded to have forward compatible implementations.
type UnimplementedPostsServer struct {
}

func (*UnimplementedPostsServer) Add(ctx context.Context, req *PostAndUserId) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedPostsServer) List(ctx context.Context, req *PostByUserId) (*PostList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterPostsServer(s *grpc.Server, srv PostsServer) {
	s.RegisterService(&_Posts_serviceDesc, srv)
}

func _Posts_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostAndUserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Posts/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServer).Add(ctx, req.(*PostAndUserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Posts_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostByUserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Posts/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServer).List(ctx, req.(*PostByUserId))
	}
	return interceptor(ctx, in, info, handler)
}

var _Posts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.Posts",
	HandlerType: (*PostsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Posts_Add_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Posts_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/model/post.proto",
}
